version: '3'
services:
  mysql:
    image: mysql:5.6.46
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test_db"
      MYSQL_ROOT_PASSWORD: "THE_PASSWORD"
    volumes:
      - mysql-datavolume:/var/lib/mysql
volumes:
  mysql-datavolume: